version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: laravel-dev
        ports:
            - "8000:8000"  # Laravel artisan serve
            - "5173:5173"  # Vite dev server
        volumes:
            - .:/var/www/html
            - ./vendor:/var/www/html/vendor
            - ./node_modules:/var/www/html/node_modules
        working_dir: /var/www/html
        command: >
            bash -c "composer install &&
                     npm install &&
                     php artisan serve --host=0.0.0.0 --port=8000 &
                     npm run dev"
