services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: laravel-dev
    ports:
      - "8000:8000"   # Laravel
      - "5173:5173"   # Vite
    volumes:
      - .:/var/www/html
      - node_modules:/var/www/html/node_modules
      - vendor:/var/www/html/vendor
    working_dir: /var/www/html
    command: >
      bash -c "composer install &&
               npm install &&
               php artisan serve --host=0.0.0.0 --port=8000 &
               npm run dev"

volumes:
  node_modules:
  vendor:
